
__problem_title__ = "Distinct powers"
__problem_url___ = "https://projecteuler.net/problem=29"
__problem_description__ = "Consider all integer combinations of for 2 ≤ ≤ 5 and 2 ≤ ≤ 5: If they " \
                          "are then placed in numerical order, with any repeats removed, we get " \
                          "the following sequence of 15 distinct terms: 4, 8, 9, 16, 25, 27, 32, " \
                          "64, 81, 125, 243, 256, 625, 1024, 3125 How many distinct terms are in " \
                          "the sequence generated by for 2 ≤ ≤ 100 and 2 ≤ ≤ 100?"

import timeit


class Solution():

    @staticmethod
    def solution1():
        pass

    @staticmethod
    def time_solutions():
        setup = 'from __main__ import Solution'
        print('Solution 1:', timeit.timeit('Solution.solution1()', setup=setup, number=1))


if __name__ == '__main__':
    s = Solution()
    print(s.solution1())
    s.time_solutions()

