
__problem_title__ = "Triangular, pentagonal, and hexagonal"
__problem_url___ = "https://projecteuler.net/problem=45"
__problem_description__ = "Triangle, pentagonal, and hexagonal numbers are generated by the " \
                          "following formulae: It can be verified that T = P = H = 40755. Find " \
                          "the next triangle number that is also pentagonal and hexagonal."

import timeit


class Solution():

    @staticmethod
    def solution1():
        pass

    @staticmethod
    def time_solutions():
        setup = 'from __main__ import Solution'
        print('Solution 1:', timeit.timeit('Solution.solution1()', setup=setup, number=1))


if __name__ == '__main__':
    s = Solution()
    print(s.solution1())
    s.time_solutions()

