
__problem_title__ = "An enormous factorial"
__problem_url___ = "https://projecteuler.net/problem=288"
__problem_description__ = "For any prime the number N( , ) is defined by N( , ) = ∑ T * with T " \
                          "generated by the following random number generator: S = 290797 S = S " \
                          "mod 50515093 T = S mod Let Nfac( , ) be the factorial of N( , ). Let " \
                          "NF( , ) be the number of factors in Nfac( , ). You are given that " \
                          "NF(3,10000) mod 3 =624955285. Find NF(61,10 ) mod 61"

import timeit


class Solution():

    @staticmethod
    def solution1():
        pass

    @staticmethod
    def time_solutions():
        setup = 'from __main__ import Solution'
        print('Solution 1:', timeit.timeit('Solution.solution1()', setup=setup, number=1))


if __name__ == '__main__':
    s = Solution()
    print(s.solution1())
    s.time_solutions()

